export const homeObjOne = {
  id: 'about',
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: 'Jiesen Zhang',
  headline: 'About Me',
  description: '_________',
  buttonLabel: 'Get Started',
  imgStart: false,
  img: require('../../images/education.svg'),
  alt: 'Car',
  dark: true,
  primary: true,
  darkText: false,
}

export const homeObjTwo = {
  id: 'education',
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: 'Education',
  headline: 'College',
  description: '_________',
  buttonLabel: 'Learn More',
  imgStart: false,
  img: require('../../images/education.svg'),
  alt: 'Car',
  dark: false,
  primary: false,
  darkText: true,
}

export const homeObjThree = {
  id: 'projects',
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: '',
  headline: 'Projects',
  description: '_________',
  buttonLabel: 'Get Started',
  imgStart: false,
  img: require('../../images/education.svg'),
  alt: 'Car',
  dark: true,
  primary: true,
  darkText: false,
}